### PR TITLE
Mark plugin as pure

### PR DESCRIPTION
**Pull request by expipiplus1**
To avoid forcing unnecessary recompiles

I haven't actually read the source in enough detail to know if this
plugin is pure, but I'd be astonished if it isn't!

### CODE REVIEW

**Comment by mkloczko** [comment]
Thanks! The only thing that could be added is ```#ifdef``` to support older GHC versions.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by expipiplus1** [comment]
Could I trouble you to make a release with this change please?

**Comment by mkloczko** [comment]
Sure, done! 0.2.3.2 had a bug in it, so it's 0.2.3.3

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
