### PR TITLE
Add GHC-9.6 support

### LINKED ISSUE #11: Support GHC-9.6
Hi, trying to build this library with the latest GHC produces the following errors:

```
src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:32:34: error:
    Module ‘GHC.Core.Opt.Monad’ does not export ‘CoreToDo(..)’
   |
32 | import GHC.Core.Opt.Monad (CoreM,CoreToDo(..))
   |                                  ^^^^^^^^^^^^
src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:72:37: error:
    Module ‘GHC.Core.TyCo.Rep’ does not export ‘TyBinder(..)’
   |
72 | import GHC.Core.TyCo.Rep (Type(..), TyBinder(..), TyCoBinder(..),scaledThing)
   |                                     ^^^^^^^^^^^^
src/Foreign/Storable/Generic/Plugin/Internal/Helpers.hs:72:51: error:
    Module ‘GHC.Core.TyCo.Rep’ does not export ‘TyCoBinder(..)’
   |
72 | import GHC.Core.TyCo.Rep (Type(..), TyBinder(..), TyCoBinder(..),scaledThing)
   | 
```

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Fixes #11

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Well, I haven't tried the change, this simply fix the compilation errors.

**Comment by mkloczko** [comment]
Thanks! There's seems to be a typo in line 44 for ```Foreign/Storable/Generic/Plugin/Internal.hs```: there is```CoreTodo``` instead of ```CoreToDo```. Should I merge this PR into a separate branch and fix this or should we wait for a fix?

**Comment by TristanCacqueray** [comment]
Oops, and sorry for the white-space changes. I can squash the commits if you prefer.

**Comment by mkloczko** [comment]
It's okay! ~~Will squash it through GitHub~~ forgot to do so.

**Pull request merged**
